services:
  api:
    container_name: go-class-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: graph-api
    ports:
      - "8082:8082"
      - "9092:9092"

  mongodb_class:
    container_name: mongodb_class
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example