apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-trigger-template
  namespace: bramterlouw-dev
spec:
  params:
    - name: IMAGE-REGISTRY-URL
      description: the registry url.
    - name: GITHUB-URL
      description: the git repository url.
    - name: PIPELINE-NAME
      description: the pipeline to be run.
  resourceTemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-run-
        namespace: bramterlouw-dev
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: "$(tt.params.PIPELINE-NAME)-pipeline"
        params:
          - name: GITHUB-URL
            value: $(tt.params.GITHUB-URL)
          - name: IMAGE-REGISTRY-URL
            value: $(tt.params.IMAGE-REGISTRY-URL)
        workspaces:
          - name: docker-credentials
            secret:
              secretName: quay-registry-secret
          - name: source
            persistentVolumeClaim:
              claimName: claim1
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
  namespace: bramterlouw-dev
spec:
  params:
    - name: GITHUB-URL
      value: "$(body.GITHUB-URL)"
    - name: IMAGE-REGISTRY-URL
      value: "$(body.IMAGE-REGISTRY-URL)"
    - name: PIPELINE-NAME
      value: "$(body.PIPELINE-NAME)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-event-listener
  namespace: bramterlouw-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: pipeline-binding
      template:
        ref: pipeline-trigger-template