apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ms-pipeline-run
  namespace: bramterlouw-dev
spec:
  params:
    - name: GITHUB-URL
      value: /Language-Fitness/School-Microservice
    - name: IMAGE-REGISTRY-URL
      value: quay.io/bramterlouw/school-microservice
  pipelineRef:
    name: ms-pipeline
  timeout: 1h0m0s
  workspaces:
    - name: docker-credentials
      secret:
        secretName: quay-registry-secret
    - name: source
      persistentVolumeClaim:
        claimName: claim1