apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-secret
data:
  config.json: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJZbkpoYlhSbGNteHZkWGNyYjNCbGJuTm9hV1owY0dsd1pXeHBibVU2TVZGV01ESlJSVFZOTmpSR1NsRTFWMUl3VTB3NVVUTlRVa2xOUWpoS1RUSmFXVEJXUkV0RFIxWTFSbGhhTTBsRVJ6TkNWVEpITnpkT1NWRlNXVTFIV2c9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
