apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  name: datasource.yaml
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: prometheus
    type: prometheus
    url: 'http://prometheus-operated:9090'
    version: 1