apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-microservice-deployment
  namespace: bramterlouw-dev
  labels:
    app.kubernetes.io/part-of: module-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: module-microservice-deployment
      app: module-microservice-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: module-microservice-deployment
        app: module-microservice-app
        project: language-fitness
    spec:
      containers:
        - name: module-microservice
          image: microservice_image
          ports:
            - containerPort: 8081
            - containerPort: 9091
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 5
            httpGet:
              path: "/health/ready"
              port: 8081
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/health/live"
              port: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: module-microservice-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: module-microservice-service
    app: module-microservice-app
    project: language-fitness
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: tcp
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    name: module-microservice-deployment
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: module-microservice-route
  namespace: bramterlouw-dev
  labels:
    name: module-microservice-route
    app: module-microservice-app
    project: language-fitness
spec:
  port:
    targetPort: 8081
  to:
    kind: Service
    name: module-microservice-service