apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-microservice
  template:
    metadata:
      labels:
        app: class-microservice
    spec:
      containers:
        - name: class-microservice
          image: microservice_image
          ports:
            - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: class-microservice-service
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: class-microservice
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: class-microservice
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: class-microservice-route
  labels:
    app: class-microservice
spec:
  port:
    targetPort: 8082
  to:
    kind: Service
    name: class-microservice-service