apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bramterlouw-dev

resources:
  - assets/website.yml

images:
  - name: cloud-cms
    newName: quay.io/bramterlouw/cloud-cms
    newTag: v1.0.0-20240118.1552
