apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: bramterlouw-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
