apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-microservice-deployment
  namespace: bramterlouw-dev
  labels:
    app.kubernetes.io/part-of: exercise-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exercise-microservice-deployment
      app: exercise-microservice-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: exercise-microservice-deployment
        app: exercise-microservice-app
        project: language-fitness
    spec:
      containers:
        - name: exercise-microservice
          image: microservice_image
          ports:
            - containerPort: 8084
            - containerPort: 9095
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 5
            httpGet:
              path: "/health/ready"
              port: 8084
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/health/live"
              port: 8084
---
kind: Service
apiVersion: v1
metadata:
  name: exercise-microservice-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: exercise-microservice-service
    app: exercise-microservice-app
    project: language-fitness
spec:
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: tcp
      port: 9095
      targetPort: 9095
      protocol: TCP
  selector:
    name: exercise-microservice-deployment
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: exercise-microservice-route
  namespace: bramterlouw-dev
  labels:
    name: exercise-microservice-route
    app: exercise-microservice-app
    project: language-fitness
spec:
  port:
    targetPort: 8084
  to:
    kind: Service
    name: exercise-microservice-service