apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-microservice-deployment
  namespace: bramterlouw-dev
  labels:
    app.kubernetes.io/part-of: exercise-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exercise-microservice-deployment
      app: exercise-microservice-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: exercise-microservice-deployment
        app: exercise-microservice-app
        project: language-fitness
    spec:
      containers:
        - name: exercise-microservice
          image: microservice_image
          ports:
            - containerPort: 8084
            - containerPort: 9095
          resources:
            limits:
              memory: 60Mi
              cpu: 50m
            requests:
              memory: 40Mi
              cpu: 20m
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 5
            httpGet:
              path: "/health/ready"
              port: 8084
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/health/live"
              port: 8084
---
kind: Service
apiVersion: v1
metadata:
  name: exercise-microservice-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: exercise-microservice-service
    app: exercise-microservice-app
    project: language-fitness
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: tcp
      port: 9095
      targetPort: 9095
      protocol: TCP
  selector:
    name: exercise-microservice-deployment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exercise-microservice-hpa
  namespace: bramterlouw-dev
  labels:
    name: exercise-microservice-hpa
    app: exercise-microservice-app
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exercise-microservice-deployment