apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-db
spec:
  serviceName: mariadb-db-service
  selector:
    matchLabels:
      app: mariadb-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-db
    spec:
      containers:
        - name: mariadb-db
          image: mariadb:latest
          volumeMounts:
            - mountPath: /data
              name: data-volume
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: testpassword
            - name: MYSQL_DATABASE
              value: keycloak
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-db
spec:
  selector:
    app: mariadb-db
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
