services:
  api:
    container_name: go-api-exercise
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: graph-api
    ports:
      - "8084:8084"

  mongodb_exercise:
    container_name: mongodb_exercise
    image: mongo
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example