kind: Deployment
apiVersion: apps/v1
metadata:
  name: gandalf-the-gateway-deployment
  namespace: bramterlouw-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gandalf-the-gateway-deployment
      app: gandalf-the-gateway-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: gandalf-the-gateway-deployment
        app: gandalf-the-gateway-app
        project: language-fitness
    spec:
      containers:
        - name: gandalf-the-gateway
          image: gateway_image
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "250Mi"
              cpu: 50m
            requests:
              memory: 100Mi
              cpu: 20m
---
kind: Service
apiVersion: v1
metadata:
  name: gandalf-the-gateway-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: gandalf-the-gateway-service
    app: gandalf-the-gateway-app
    project: language-fitness
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    name: gandalf-the-gateway-deployment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gandalf-the-gateway-hpa
  namespace: bramterlouw-dev
  labels:
    name: gandalf-the-gateway-hpa
    app: gandalf-the-gateway-app
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gandalf-the-gateway-deployment