kind: Deployment
apiVersion: apps/v1
metadata:
  name: gandalf-the-gateway-deployment
  namespace: bramterlouw-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gandalf-the-gateway-deployment
      app: gandalf-the-gateway-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: gandalf-the-gateway-deployment
        app: gandalf-the-gateway-app
        project: language-fitness
    spec:
      containers:
        - name: gandalf-the-gateway
          image: gateway_image
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "250Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: gandalf-the-gateway-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: gandalf-the-gateway-service
    app: gandalf-the-gateway-app
    project: language-fitness
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    name: gandalf-the-gateway-deployment
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gandalf-the-gateway-route
  namespace: bramterlouw-dev
  labels:
    name: gandalf-the-gateway-route
    app: gandalf-the-gateway-app
    project: language-fitness
spec:
  port:
    targetPort: 4000
  to:
    kind: Service
    name: gandalf-the-gateway-service