apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-microservice
  template:
    metadata:
      labels:
        app: school-microservice
    spec:
      containers:
        - name: school-microservice
          image: microservice_image
          ports:
            - containerPort: 8083
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 3
            httpGet:
              path: "/healthz"
              port: 8082
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/healthz"
              port: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: school-microservice-service
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: school-microservice
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  selector:
    app: school-microservice
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: school-microservice-route
  labels:
    app: school-microservice
spec:
  port:
    targetPort: 8083
  to:
    kind: Service
    name: school-microservice-service