apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-microservice
      project: language-fitness
  template:
    metadata:
      labels:
        app: openai-microservice
        project: language-fitness
    spec:
      containers:
        - name: openai-microservice
          image: microservice_image
          ports:
            - containerPort: 4000
#          readinessProbe:
#            timeoutSeconds: 3
#            initialDelaySeconds: 15
#            httpGet:
#              path: "/health/ready"
#              port: 4000
#          livenessProbe:
#            timeoutSeconds: 3
#            initialDelaySeconds: 30
#            httpGet:
#              path: "/health/live"
#              port: 4000
---
kind: Service
apiVersion: v1
metadata:
  name: openai-microservice-service
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: openai-microservice
    project: language-fitness
spec:
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: openai-microservice
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openai-microservice-route
  labels:
    app: openai-microservice
    project: language-fitness
spec:
  port:
    targetPort: 4000
  to:
    kind: Service
    name: openai-microservice-service