services:
  api:
    container_name: go-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: graph-api
    ports:
      - "8080:8080"
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example