version: '3'

services:
  go-api-test:
    container_name: go-api-test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: graph-api-test
    ports:
      - "8081:8081"
    depends_on:
      - mongodb_test

  mongodb_test:
    container_name: mongodb_test
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
