apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-instance
  namespace: monitoring
  labels:
    name: prometheus-instance
    app: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus-sa
  securityContext: {}
  serviceMonitorSelector:
    matchLabels:
      name: prometheus-service-monitor
    ruleSelector: {}