kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: prometheus-route
  namespace: grafana
  labels:
    name: prometheus-route
    app: prometheus
    project: language-fitness
    operated-prometheus: "true"
spec:
  path: /
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None