apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-issuer-v2
  namespace: bramterlouw-dev
spec:
  acme:
    email: bramterlouw12@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik