apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-microservice-deployment
  namespace: bramterlouw-dev
  labels:
    app.kubernetes.io/part-of: result-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-microservice-deployment
      app: result-microservice-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: result-microservice-deployment
        app: result-microservice-app
        project: language-fitness
    spec:
      containers:
        - name: result-microservice
          image: microservice_image
          ports:
            - containerPort: 8085
            - containerPort: 9094
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 5
            httpGet:
              path: "/health/ready"
              port: 8085
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/health/live"
              port: 8085
---
kind: Service
apiVersion: v1
metadata:
  name: result-microservice-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: result-microservice-service
    app: result-microservice-app
    project: language-fitness
spec:
  ports:
    - name: http
      port: 8085
      targetPort: 8085
    - name: tcp
      port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    name: result-microservice-deployment
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: result-microservice-route
  namespace: bramterlouw-dev
  labels:
    name: result-microservice-route
    app: result-microservice-app
    project: language-fitness
spec:
  port:
    targetPort: 8085
  to:
    kind: Service
    name: result-microservice-service