kind: Deployment
apiVersion: apps/v1
metadata:
  name: gandalf-the-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gandalf-the-gateway
  template:
    metadata:
      labels:
        app: gandalf-the-gateway
    spec:
      containers:
        - name: gandalf-the-gateway
          image: gateway_image
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "250Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: gandalf-the-gateway-service
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: gandalf-the-gateway
spec:
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: gandalf-the-gateway