apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application-monitor
  namespace: monitoring
  labels:
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - bramterlouw-dev
  selector:
    matchLabels:
      project: language-fitness
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
