apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-instance
  namespace: monitoring
  labels:
    name: prometheus-instance
    app: prometheus
    project: language-fitness
spec:
  replicas: 2
  serviceAccountName: prometheus-sa
  securityContext: {}
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
    ruleSelector: {}