apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: monitoring
  labels:
    name: prometheus-service-monitor
    app: prometheus
    project: language-fitness
spec:
  namespaceSelector:
    matchNames:
      - bramterlouw-dev
  selector:
    matchLabels:
      project: language-fitness
  endpoints:
    - port: http
      path: /metrics
      interval: 30s