apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-microservice-deployment
  namespace: bramterlouw-dev
  labels:
    app.kubernetes.io/part-of: saga-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: saga-microservice-deployment
      app: saga-microservice-app
      project: language-fitness
  template:
    metadata:
      labels:
        name: saga-microservice-deployment
        app: saga-microservice-app
        project: language-fitness
    spec:
      containers:
        - name: saga-microservice
          image: microservice_image
          ports:
            - containerPort: 8083
            - containerPort: 9090
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 5
            httpGet:
              path: "/health/ready"
              port: 8083
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/health/live"
              port: 8083
---
kind: Service
apiVersion: v1
metadata:
  name: saga-microservice-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: saga-microservice-service
    app: saga-microservice-app
    project: language-fitness
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: tcp
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    name: saga-microservice-deployment
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: saga-microservice-route
  namespace: bramterlouw-dev
  labels:
    name: saga-microservice-route
    app: saga-microservice-app
    project: language-fitness
spec:
  port:
    targetPort: 8083
  to:
    kind: Service
    name: saga-microservice-service