kind: Service
apiVersion: v1
metadata:
  name: saga-mongodb-service
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: saga-mongodb
spec:
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
  selector:
    app: saga-mongodb