kind: Service
apiVersion: v1
metadata:
  name: saga-mongodb-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: saga-mongodb-service
    app: saga-microservice-app
    project: language-fitness
spec:
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
  selector:
    name: saga-mongodb