apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ingres-cert
  namespace: bramterlouw-dev
spec:
  secretName: keycloak-temp-cert
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - example-keycloak-bramterlouw-dev.apps.ocp2-inholland.joran-bergfeld.com
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io