kind: Deployment
apiVersion: apps/v1
metadata:
  name: vue-cloud-cms
  namespace: bramterlouw-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vue-cloud-cms
      app: vue-cloud-cms
  template:
    metadata:
      labels:
        name: vue-cloud-cms
        app: vue-cloud-cms
    spec:
      containers:
        - name: vue-cloud-cms-container
          image: cloud-cms
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "250Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: vue-cloud-cms-service
  namespace: bramterlouw-dev
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: vue-cloud-cms-service
    app: vue-cloud-cms
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    name: vue-cloud-cms
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vue-cloud-cms-route
  namespace: bramterlouw-dev
  labels:
    name: vue-cloud-cms-route
    app: vue-cloud-cms
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: vue-cloud-cms-service