kind: Deployment
apiVersion: apps/v1
metadata:
  name: graph-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-api
  template:
    metadata:
      labels:
        app: graph-api
    spec:
      containers:
        - name: graph-api
          image: marbwoulret/graph-api:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "20Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: graph-api
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: graph-api
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: graph-api
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: graph-api
  labels:
    app: graph-api
spec:
  port:
    targetPort: 8081
  to:
    kind: Service
    name: graph-api