services:
  api:
    container_name: go-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: graph-api
    ports:
      - "8083:8083"

  mongodb:
    container_name: mongodb
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example